# Pandas Tutorial

In [3]:
import pandas as pd

a =pd.DataFrame({'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
                 'Age': [25, 30, 35, 40, 45]})
a

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40
4      Eve   45

In [4]:
data = [1,2,3,4,5]
s = pd.Series(data)
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64

# DataFrame

In [4]:
df= pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns=['A','B','C'], index=['Row1','Row2','Row3'])
print(df)

      A  B  C
Row1  1  2  3
Row2  4  5  6
Row3  7  8  9

In [16]:
obesity_data = pd.read_csv('obesity_prediction.csv')
obesity_data.sample(10)

,Student_ID,Name,Age,Gender,Height_cm,Weight_kg,BMI,Marks,Exercise_hours_per_week,Daily_calorie_intake,Sleep_hours,Family_history_obesity,Fast_food_meals_per_week,Water_liters_per_day,Obesity_Level
47,48,Mahi Mehra,18,Female,153,55,23.5,85,4,2100,7.0,No,1,2.3,Normal
38,39,Parth Arora,18,Male,170,74,25.6,71,2,2650,6.0,No,3,1.9,Overweight
19,20,Riya Bansal,18,Female,163,50,18.8,87,4,1950,7.5,No,0,2.5,Normal
40,41,Aditya Nanda,17,Male,182,98,29.6,65,1,3350,6.0,Yes,5,1.5,Overweight
37,38,Sanya Saxena,17,Female,164,69,25.7,73,2,2550,6.5,Yes,3,1.8,Overweight
9,10,Diya Shah,16,Female,151,39,17.1,93,7,1650,8.5,No,0,2.2,Underweight
45,46,Aisha Qureshi,19,Female,166,73,26.5,72,2,2650,6.5,Yes,4,1.7,Overweight
11,12,Saanvi Joshi,17,Female,160,59,23.0,82,3,2200,7.0,No,2,2.0,Normal
39,40,Jiya Narang,19,Female,155,58,24.1,84,4,2150,7.5,No,1,2.4,Normal
5,6,Kavya Nair,17,Female,155,45,18.7,88,4,1850,7.0,No,1,2.1,Normal